// Generator content collection datoteka za bicikle.
// Podaci su ovdje na jednom mjestu, izlaz su .md datoteke koje klijent uređuje.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const OUT = process.argv[2];
mkdirSync(OUT, { recursive: true });

const P = (d1, d2, d4, d7, d14) => ({ d1, d2, d4, d7, d14 });

const fleet = [
  // ── E-BIKES ──────────────────────────────────────────────────────────
  {
    slug: 'apache-hupahu', sku: 'EB-APA-HUPAHU', category: 'e-bike', brand: 'Apache',
    order: 1, featured: true, fleetSize: 4, image: 'e-bike-APACHE-HUPAHU.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 9, suspension: 'hardtail',
      brakes: 'hydraulic-disc', motor: 'mid-250', battery: 'integrated',
      range: '60–90 km', sizes: ['M', 'L'], riderHeight: [170, 190] },
    pricing: P(35, 32, 29, 26, 23),
    needsReview: ['motor', 'battery', 'range', 'gears'],
    color: { hr: 'mentol', en: 'mint', de: 'Mint', it: 'menta' },
    i18n: {
      hr: { name: 'Apache Hupahu', tagline: 'Električni brdski, 29″',
        description: 'Hardtail e-MTB s motorom u sredini i baterijom skrivenom u okviru — težina je nisko i bicikl se u zavoju ponaša normalno, ne kao moped. Schwalbe gume za makadam, hidraulične disk kočnice. Ovo je bicikl kojim se cijeli Kamenjak odvozi bez razmišljanja o usponima.',
        highlights: ['Motor u sredini, ne u kotaču', 'Baterija u okviru', 'Gume za makadam', 'Hidraulične disk kočnice'] },
      en: { name: 'Apache Hupahu', tagline: 'Electric mountain bike, 29″',
        description: 'A hardtail e-MTB with a mid-drive motor and the battery hidden in the frame — the weight sits low and the bike still handles like a bike, not a moped. Schwalbe gravel-capable tyres, hydraulic disc brakes. This is the one that gets you around all of Kamenjak without a thought for the climbs.',
        highlights: ['Mid-drive motor, not a hub', 'Battery integrated in the frame', 'Gravel-capable tyres', 'Hydraulic disc brakes'] },
      de: { name: 'Apache Hupahu', tagline: 'E-Mountainbike, 29″',
        description: 'Ein Hardtail-E-MTB mit Mittelmotor und im Rahmen integriertem Akku — der Schwerpunkt liegt tief, das Rad fährt sich wie ein Rad und nicht wie ein Moped. Schwalbe-Reifen für Schotter, hydraulische Scheibenbremsen. Damit fährt man den ganzen Kamenjak, ohne über Anstiege nachzudenken.',
        highlights: ['Mittelmotor statt Nabenmotor', 'Akku im Rahmen integriert', 'Schottertaugliche Reifen', 'Hydraulische Scheibenbremsen'] },
      it: { name: 'Apache Hupahu', tagline: 'Mountain bike elettrica, 29″',
        description: 'Una e-MTB front con motore centrale e batteria integrata nel telaio: il peso resta basso e la bici si guida come una bici, non come un ciclomotore. Gomme Schwalbe adatte allo sterrato, freni a disco idraulici. È quella con cui si gira tutto il Kamenjak senza pensare alle salite.',
        highlights: ['Motore centrale, non al mozzo', 'Batteria integrata nel telaio', 'Gomme adatte allo sterrato', 'Freni a disco idraulici'] },
    },
  },
  {
    slug: 'apache-tuwan', sku: 'EB-APA-TUWAN', category: 'e-bike', brand: 'Apache',
    order: 2, featured: true, fleetSize: 4, image: 'e-bike-APACHE-TUWAN.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 9, suspension: 'hardtail',
      brakes: 'hydraulic-disc', motor: 'mid-250', battery: 'integrated',
      range: '60–90 km', sizes: ['M', 'L', 'XL'], riderHeight: [172, 195] },
    pricing: P(35, 32, 29, 26, 23),
    needsReview: ['motor', 'battery', 'range', 'gears'],
    color: { hr: 'tamnozelena', en: 'dark green', de: 'Dunkelgrün', it: 'verde scuro' },
    i18n: {
      hr: { name: 'Apache Tuwan', tagline: 'Električni brdski, 29″',
        description: 'Ista provjerena platforma kao Hupahu, ali u većim okvirima — za vozače od 180 cm naviše. Impac Smartpac gume podjednako dobro drže na asfaltu i na makadamu, pa je ovo dobar izbor ako dan počinje u gradu, a završava na šumskom putu.',
        highlights: ['Okviri do XL', 'Univerzalne gume asfalt/makadam', 'Motor u sredini', 'Amortizirajuća vilica'] },
      en: { name: 'Apache Tuwan', tagline: 'Electric mountain bike, 29″',
        description: 'The same proven platform as the Hupahu but in larger frames — for riders from 180 cm up. Impac Smartpac tyres grip equally well on tarmac and gravel, so this is the pick when the day starts in town and ends on a forest track.',
        highlights: ['Frames up to XL', 'All-round tarmac/gravel tyres', 'Mid-drive motor', 'Suspension fork'] },
      de: { name: 'Apache Tuwan', tagline: 'E-Mountainbike, 29″',
        description: 'Dieselbe bewährte Plattform wie das Hupahu, nur in größeren Rahmen — für Fahrer ab 180 cm. Impac-Smartpac-Reifen greifen auf Asphalt wie auf Schotter, ideal wenn der Tag in der Stadt beginnt und auf dem Waldweg endet.',
        highlights: ['Rahmen bis XL', 'Allround-Reifen Asphalt/Schotter', 'Mittelmotor', 'Federgabel'] },
      it: { name: 'Apache Tuwan', tagline: 'Mountain bike elettrica, 29″',
        description: 'La stessa piattaforma collaudata della Hupahu ma con telai più grandi — per chi supera i 180 cm. Le gomme Impac Smartpac tengono bene sia su asfalto sia su sterrato: la scelta giusta se la giornata inizia in città e finisce su una strada forestale.',
        highlights: ['Telai fino alla XL', 'Gomme miste asfalto/sterrato', 'Motore centrale', 'Forcella ammortizzata'] },
    },
  },
  {
    slug: 'apache-yamka', sku: 'EB-APA-YAMKA', category: 'e-bike', brand: 'Apache',
    order: 3, featured: false, fleetSize: 3, image: 'e-bike-APACHE-YAMKA.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'lowstep', gears: 9, suspension: 'hardtail',
      brakes: 'hydraulic-disc', motor: 'mid-250', battery: 'integrated',
      range: '60–90 km', sizes: ['S', 'M'], riderHeight: [160, 178] },
    pricing: P(35, 32, 29, 26, 23),
    needsReview: ['motor', 'battery', 'range', 'gears'],
    color: { hr: 'plava', en: 'blue', de: 'Blau', it: 'blu' },
    i18n: {
      hr: { name: 'Apache Yamka', tagline: 'Električni brdski, sniženi okvir',
        description: 'Yamka je Hupahu sa sniženom gornjom cijevi — lakše se sjeda i silazi, što na dugoj vožnji s puno zaustavljanja mijenja sve. Namijenjen manjim vozačima i svima koji ne žele prebacivati nogu preko visokog okvira.',
        highlights: ['Sniženi okvir, lakši ulazak', 'Za visinu 160–178 cm', 'Motor u sredini', 'Hidraulične disk kočnice'] },
      en: { name: 'Apache Yamka', tagline: 'Electric mountain bike, low step-over',
        description: 'The Yamka is a Hupahu with a lowered top tube — easier to get on and off, which changes everything on a long day with lots of stops. Built for smaller riders and anyone who would rather not swing a leg over a high frame.',
        highlights: ['Low step-over frame', 'For riders 160–178 cm', 'Mid-drive motor', 'Hydraulic disc brakes'] },
      de: { name: 'Apache Yamka', tagline: 'E-Mountainbike, tiefer Einstieg',
        description: 'Das Yamka ist ein Hupahu mit abgesenktem Oberrohr — leichteres Auf- und Absteigen, was auf langen Tagen mit vielen Stopps den Unterschied macht. Für kleinere Fahrerinnen und Fahrer und alle, die nicht über einen hohen Rahmen steigen wollen.',
        highlights: ['Tiefer Einstieg', 'Für 160–178 cm', 'Mittelmotor', 'Hydraulische Scheibenbremsen'] },
      it: { name: 'Apache Yamka', tagline: 'Mountain bike elettrica, telaio basso',
        description: 'La Yamka è una Hupahu con tubo orizzontale ribassato: si sale e si scende più facilmente, e in una giornata lunga con molte soste cambia tutto. Pensata per chi è più basso di statura e per chi preferisce non scavalcare un telaio alto.',
        highlights: ['Telaio a entrata bassa', 'Per statura 160–178 cm', 'Motore centrale', 'Freni a disco idraulici'] },
    },
  },
  {
    slug: 'crussis-e-cross', sku: 'EB-CRU-CROSS', category: 'e-bike', brand: 'Crussis',
    order: 4, featured: false, fleetSize: 3, image: 'e-bike-CRUSSIS.jpg',
    specs: { wheel: '28', frameMaterial: 'aluminium', frameType: 'stepthrough', gears: 9, suspension: 'hardtail',
      brakes: 'hydraulic-disc', motor: 'mid-250', battery: 'integrated',
      range: '70–100 km', sizes: ['S', 'M', 'L'], riderHeight: [158, 185] },
    pricing: P(33, 30, 27, 24, 22),
    needsReview: ['motor', 'battery', 'range', 'gears'],
    color: { hr: 'smeđa', en: 'brown', de: 'Braun', it: 'marrone' },
    i18n: {
      hr: { name: 'Crussis e-Cross', tagline: 'Električni trekking, 28″',
        description: 'Prohodni okvir i gume s glatkom sredinom — brz na asfaltu, siguran na utabanom makadamu. Uspravniji položaj od brdskog bicikla, pa leđa i vrat izdrže i peti dan zaredom. Najčešći izbor za obilaske uz obalu.',
        highlights: ['Prohodni okvir', 'Uspravan, udoban položaj', 'Brze trekking gume', 'Domet do 100 km'] },
      en: { name: 'Crussis e-Cross', tagline: 'Electric trekking bike, 28″',
        description: 'A step-through frame and tyres with a smooth centre strip — quick on tarmac, sure-footed on packed gravel. A more upright position than a mountain bike, so your back and neck survive day five as well. The usual pick for exploring along the coast.',
        highlights: ['Step-through frame', 'Upright, comfortable position', 'Fast trekking tyres', 'Range up to 100 km'] },
      de: { name: 'Crussis e-Cross', tagline: 'E-Trekkingrad, 28″',
        description: 'Tiefeinsteiger-Rahmen und Reifen mit glatter Mittellauffläche — schnell auf Asphalt, sicher auf festem Schotter. Aufrechtere Sitzposition als beim Mountainbike, sodass Rücken und Nacken auch am fünften Tag mitmachen. Die übliche Wahl für Touren entlang der Küste.',
        highlights: ['Tiefeinsteiger-Rahmen', 'Aufrechte, bequeme Position', 'Schnelle Trekkingreifen', 'Reichweite bis 100 km'] },
      it: { name: 'Crussis e-Cross', tagline: 'Bici elettrica da trekking, 28″',
        description: 'Telaio a scavalco basso e gomme con battistrada centrale liscio: veloce sull’asfalto, sicura sullo sterrato compatto. Posizione più eretta rispetto a una mountain bike, così schiena e collo reggono anche al quinto giorno. La scelta abituale per girare lungo la costa.',
        highlights: ['Telaio a scavalco basso', 'Posizione eretta e comoda', 'Gomme da trekking veloci', 'Autonomia fino a 100 km'] },
    },
  },
  {
    slug: 'venda-vam-grand-touring', sku: 'EB-VEN-VAM', category: 'e-bike', brand: 'Venda',
    order: 5, featured: true, fleetSize: 4, image: 'e-bike-VENDA-VAM.jpg',
    specs: { wheel: '28', frameMaterial: 'aluminium', frameType: 'trekking', gears: 8, suspension: 'hardtail',
      brakes: 'hydraulic-disc', motor: 'mid-250', battery: 'integrated',
      range: '70–110 km', sizes: ['M', 'L'], riderHeight: [168, 190] },
    pricing: P(33, 30, 27, 24, 22),
    needsReview: ['motor', 'battery', 'range', 'gears'],
    color: { hr: 'crna/crvena', en: 'black/red', de: 'Schwarz/Rot', it: 'nero/rosso' },
    i18n: {
      hr: { name: 'Venda VAM Grand Touring', tagline: 'Električni trekking s nosačem',
        description: 'Jedini bicikl u floti koji dolazi spreman za stvarni put: puni blatobrani, nosač prtljage i svjetla. Ako planirate cijeli dan izvan apartmana, ručak u konobi i povratak po mraku — ovo je taj bicikl.',
        highlights: ['Nosač prtljage i blatobrani', 'Svjetla u standardu', 'Domet do 110 km', 'Amortizirajuća vilica'] },
      en: { name: 'Venda VAM Grand Touring', tagline: 'Electric trekking bike with rack',
        description: 'The only bike in the fleet that arrives ready for a real journey: full mudguards, a luggage rack and lights. If you are planning a whole day out, lunch at a konoba and the ride home after dark — this is the one.',
        highlights: ['Rack and full mudguards', 'Lights as standard', 'Range up to 110 km', 'Suspension fork'] },
      de: { name: 'Venda VAM Grand Touring', tagline: 'E-Trekkingrad mit Gepäckträger',
        description: 'Das einzige Rad der Flotte, das für eine echte Tour ausgerüstet ankommt: volle Schutzbleche, Gepäckträger und Licht. Wer einen ganzen Tag unterwegs sein will, mittags in eine Konoba einkehrt und im Dunkeln zurückfährt, nimmt dieses.',
        highlights: ['Gepäckträger und Schutzbleche', 'Licht serienmäßig', 'Reichweite bis 110 km', 'Federgabel'] },
      it: { name: 'Venda VAM Grand Touring', tagline: 'Bici elettrica da trekking con portapacchi',
        description: 'L’unica bici della flotta che arriva pronta per un viaggio vero: parafanghi integrali, portapacchi e luci. Se il piano è stare fuori tutto il giorno, pranzare in konoba e rientrare col buio, è questa.',
        highlights: ['Portapacchi e parafanghi', 'Luci di serie', 'Autonomia fino a 110 km', 'Forcella ammortizzata'] },
    },
  },

  // ── MTB ──────────────────────────────────────────────────────────────
  {
    slug: 'mtb-29-stratos-grey', sku: 'MTB-BRB-STRAT-GY', category: 'mtb', brand: 'B.R.B. Sport',
    order: 10, featured: true, fleetSize: 6, image: 'mtb-29-brb-standard-grey.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 21, suspension: 'hardtail',
      brakes: 'disc', sizes: ['M', 'L'], riderHeight: [170, 190] },
    pricing: P(18, 16, 14, 13, 12),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'siva', en: 'grey', de: 'Grau', it: 'grigio' },
    i18n: {
      hr: { name: 'BRB Stratos 29 — siva', tagline: 'Brdski, 29″',
        description: 'Naš vlastiti okvir i naša montaža. Veliki kotači prelaze preko kamenja koje bi 26-inčni bicikl zaustavilo, a to je na istarskim makadamima svakih pedeset metara. Radni konj flote — najviše komada, najmanje problema.',
        highlights: ['Veliki kotači 29″', 'Amortizirajuća vilica', 'Disk kočnice', 'Najviše komada u floti'] },
      en: { name: 'BRB Stratos 29 — grey', tagline: 'Mountain bike, 29″',
        description: 'Our own frame, built up in our own workshop. The big wheels roll over the rocks that would stop a 26-inch bike, and on Istrian gravel that happens every fifty metres. The workhorse of the fleet — most units, fewest problems.',
        highlights: ['Big 29″ wheels', 'Suspension fork', 'Disc brakes', 'Most units in the fleet'] },
      de: { name: 'BRB Stratos 29 — grau', tagline: 'Mountainbike, 29″',
        description: 'Eigener Rahmen, in der eigenen Werkstatt aufgebaut. Die großen Laufräder rollen über Steine, an denen ein 26-Zoll-Rad hängen bleibt — auf istrischem Schotter alle fünfzig Meter. Das Arbeitstier der Flotte: die meisten Exemplare, die wenigsten Probleme.',
        highlights: ['Große 29″-Laufräder', 'Federgabel', 'Scheibenbremsen', 'Häufigstes Modell der Flotte'] },
      it: { name: 'BRB Stratos 29 — grigia', tagline: 'Mountain bike, 29″',
        description: 'Telaio nostro, montato nella nostra officina. Le ruote grandi passano sopra i sassi che fermerebbero una 26 pollici, e sullo sterrato istriano capita ogni cinquanta metri. Il cavallo da lavoro della flotta: più esemplari, meno problemi.',
        highlights: ['Ruote grandi da 29″', 'Forcella ammortizzata', 'Freni a disco', 'Il modello più numeroso'] },
    },
  },
  {
    slug: 'mtb-29-stratos-black', sku: 'MTB-BRB-STRAT-BK', category: 'mtb', brand: 'B.R.B. Sport',
    order: 11, featured: false, fleetSize: 6, image: 'mtb-29-brb-standard-black.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 21, suspension: 'hardtail',
      brakes: 'disc', sizes: ['M', 'L', 'XL'], riderHeight: [172, 195] },
    pricing: P(18, 16, 14, 13, 12),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'crna', en: 'black', de: 'Schwarz', it: 'nero' },
    i18n: {
      hr: { name: 'BRB Stratos 29 — crna', tagline: 'Brdski, 29″',
        description: 'Identičan Stratosu u sivoj, samo u crnoj boji i s dostupnim XL okvirom. Ako ste viši od 185 cm, ovo je model koji tražite.',
        highlights: ['Dostupan XL okvir', 'Veliki kotači 29″', 'Amortizirajuća vilica', 'Disk kočnice'] },
      en: { name: 'BRB Stratos 29 — black', tagline: 'Mountain bike, 29″',
        description: 'Identical to the grey Stratos, only in black and with an XL frame available. If you are over 185 cm, this is the one to ask for.',
        highlights: ['XL frame available', 'Big 29″ wheels', 'Suspension fork', 'Disc brakes'] },
      de: { name: 'BRB Stratos 29 — schwarz', tagline: 'Mountainbike, 29″',
        description: 'Identisch mit dem grauen Stratos, nur in Schwarz und mit verfügbarem XL-Rahmen. Wer über 185 cm groß ist, fragt nach diesem.',
        highlights: ['XL-Rahmen verfügbar', 'Große 29″-Laufräder', 'Federgabel', 'Scheibenbremsen'] },
      it: { name: 'BRB Stratos 29 — nera', tagline: 'Mountain bike, 29″',
        description: 'Identica alla Stratos grigia, solo nera e con telaio XL disponibile. Se superate i 185 cm, è questa da chiedere.',
        highlights: ['Telaio XL disponibile', 'Ruote grandi da 29″', 'Forcella ammortizzata', 'Freni a disco'] },
    },
  },
  {
    slug: 'mtb-29-seattle-hardtail', sku: 'MTB-BRB-SEATTLE', category: 'mtb', brand: 'B.R.B. Sport',
    order: 12, featured: false, fleetSize: 5, image: 'mtb-29-brb-seattle-hardtail-basic.jpg',
    specs: { wheel: '29', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 21, suspension: 'hardtail',
      brakes: 'v-brake', sizes: ['M', 'L'], riderHeight: [168, 188] },
    pricing: P(16, 15, 13, 12, 11),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'crna', en: 'black', de: 'Schwarz', it: 'nero' },
    i18n: {
      hr: { name: 'BRB Seattle 29', tagline: 'Brdski, osnovna oprema',
        description: 'Jednostavnija verzija 29-inčnog brdskog bicikla, bez viška opreme i bez viška cijene. Sve što treba za makadam i šetnice — ništa što se može pokvariti.',
        highlights: ['Povoljniji ulaz u 29″', 'Amortizirajuća vilica', 'Jednostavno održavanje'] },
      en: { name: 'BRB Seattle 29', tagline: 'Mountain bike, basic build',
        description: 'A simpler take on the 29-inch mountain bike — no extra kit and no extra cost. Everything you need for gravel and forest paths, nothing that can break.',
        highlights: ['Cheaper way into 29″', 'Suspension fork', 'Simple to maintain'] },
      de: { name: 'BRB Seattle 29', tagline: 'Mountainbike, Basisausstattung',
        description: 'Die einfachere Variante des 29-Zoll-Mountainbikes — ohne Extras und ohne Aufpreis. Alles, was man für Schotter und Waldwege braucht, nichts, was kaputtgehen kann.',
        highlights: ['Günstiger Einstieg in 29″', 'Federgabel', 'Wartungsarm'] },
      it: { name: 'BRB Seattle 29', tagline: 'Mountain bike, allestimento base',
        description: 'La versione più semplice della 29 pollici: nessun accessorio in più e nessun costo in più. Tutto quello che serve per sterrato e sentieri, niente che si possa rompere.',
        highlights: ['Ingresso economico alle 29″', 'Forcella ammortizzata', 'Manutenzione semplice'] },
    },
  },
  {
    slug: 'mtb-26-hardtail-standard', sku: 'MTB-BRB-26-HT', category: 'mtb', brand: 'B.R.B. Sport',
    order: 13, featured: false, fleetSize: 8, image: 'mtb-26-brb-hardtail-standard.jpg',
    specs: { wheel: '26', frameMaterial: 'aluminium', frameType: 'hardtail', gears: 21, suspension: 'hardtail',
      brakes: 'v-brake', sizes: ['S', 'M'], riderHeight: [155, 175] },
    pricing: P(14, 13, 11, 10, 9),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'crna', en: 'black', de: 'Schwarz', it: 'nero' },
    i18n: {
      hr: { name: 'BRB Hardtail 26', tagline: 'Brdski, 26″',
        description: 'Manji kotači i manji okviri — bicikl za tinejdžere i niže odrasle vozače kojima je 29-inčni prevelik. Okretan u uskim ulicama starog Šišana i lagan za podizanje na stepenice apartmana.',
        highlights: ['Za visinu 155–175 cm', 'Okretan i lagan', 'Amortizirajuća vilica'] },
      en: { name: 'BRB Hardtail 26', tagline: 'Mountain bike, 26″',
        description: 'Smaller wheels and smaller frames — the bike for teenagers and shorter adults for whom a 29er is simply too much. Nimble in the narrow streets of old Šišan and light enough to carry up the apartment stairs.',
        highlights: ['For riders 155–175 cm', 'Nimble and light', 'Suspension fork'] },
      de: { name: 'BRB Hardtail 26', tagline: 'Mountainbike, 26″',
        description: 'Kleinere Laufräder, kleinere Rahmen — das Rad für Jugendliche und kleinere Erwachsene, denen ein 29er schlicht zu groß ist. Wendig in den engen Gassen des alten Šišan und leicht genug für die Apartmenttreppe.',
        highlights: ['Für 155–175 cm', 'Wendig und leicht', 'Federgabel'] },
      it: { name: 'BRB Hardtail 26', tagline: 'Mountain bike, 26″',
        description: 'Ruote e telai più piccoli: la bici per ragazzi e adulti di statura contenuta a cui una 29 sta larga. Agile nelle vie strette della vecchia Šišan e leggera da portare su per le scale dell’appartamento.',
        highlights: ['Per statura 155–175 cm', 'Agile e leggera', 'Forcella ammortizzata'] },
    },
  },
  {
    slug: 'mtb-26-hystric-fully-blue', sku: 'MTB-BRB-HYS-BL', category: 'mtb', brand: 'Hystoric',
    order: 14, featured: false, fleetSize: 4, image: 'mtb-26-brb-hystric-fully-standard-basic-blue.jpg',
    specs: { wheel: '26', frameMaterial: 'aluminium', frameType: 'fully', gears: 21, suspension: 'full',
      brakes: 'disc', sizes: ['M', 'L'], riderHeight: [165, 185] },
    pricing: P(16, 15, 13, 12, 11),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'plava', en: 'blue', de: 'Blau', it: 'blu' },
    i18n: {
      hr: { name: 'Hystric Fully 26 — plavi', tagline: 'Brdski s punim ovjesom',
        description: 'Ovjes i sprijeda i straga. Na kamenjaru oko Premanture razlika se osjeti u zapešćima i leđima nakon dva sata vožnje — ovo je bicikl za one koji stvarno idu s ceste dolje.',
        highlights: ['Puni ovjes', 'Disk kočnice', 'Za tehnički zahtjevne staze'] },
      en: { name: 'Hystric Fully 26 — blue', tagline: 'Full-suspension mountain bike',
        description: 'Suspension front and rear. On the limestone around Premantura you feel the difference in your wrists and back after two hours in the saddle — this is the bike for people who actually leave the road.',
        highlights: ['Full suspension', 'Disc brakes', 'For technical trails'] },
      de: { name: 'Hystric Fully 26 — blau', tagline: 'Fully-Mountainbike',
        description: 'Federung vorn und hinten. Auf dem Karst rund um Premantura merkt man den Unterschied nach zwei Stunden in Handgelenken und Rücken — das Rad für alle, die die Straße wirklich verlassen.',
        highlights: ['Vollfederung', 'Scheibenbremsen', 'Für technische Trails'] },
      it: { name: 'Hystric Fully 26 — blu', tagline: 'Mountain bike biammortizzata',
        description: 'Sospensioni davanti e dietro. Sul carso attorno a Premantura la differenza si sente nei polsi e nella schiena dopo due ore di sella: è la bici per chi lascia davvero la strada.',
        highlights: ['Doppia sospensione', 'Freni a disco', 'Per sentieri tecnici'] },
    },
  },
  {
    slug: 'mtb-26-hystric-fully-red', sku: 'MTB-BRB-HYS-RD', category: 'mtb', brand: 'Hystoric',
    order: 15, featured: false, fleetSize: 4, image: 'mtb-26-brb-hystric-fully-standard-basic-red.jpg',
    specs: { wheel: '26', frameMaterial: 'aluminium', frameType: 'fully', gears: 21, suspension: 'full',
      brakes: 'disc', sizes: ['S', 'M'], riderHeight: [158, 178] },
    pricing: P(16, 15, 13, 12, 11),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'crvena', en: 'red', de: 'Rot', it: 'rosso' },
    i18n: {
      hr: { name: 'Hystric Fully 26 — crveni', tagline: 'Brdski s punim ovjesom',
        description: 'Isti bicikl kao plavi Hystric, u manjim okvirima. Puni ovjes u veličini S rijetkost je u najmu, a upravo on omogućuje da cijela obitelj vozi istu stazu.',
        highlights: ['Puni ovjes u veličini S', 'Disk kočnice', 'Za visinu 158–178 cm'] },
      en: { name: 'Hystric Fully 26 — red', tagline: 'Full-suspension mountain bike',
        description: 'The same bike as the blue Hystric, in smaller frames. Full suspension in a size S is rare in a rental fleet, and it is exactly what lets the whole family ride the same trail.',
        highlights: ['Full suspension in size S', 'Disc brakes', 'For riders 158–178 cm'] },
      de: { name: 'Hystric Fully 26 — rot', tagline: 'Fully-Mountainbike',
        description: 'Dasselbe Rad wie das blaue Hystric, nur in kleineren Rahmen. Ein Fully in Größe S ist im Verleih selten — und genau das lässt die ganze Familie denselben Trail fahren.',
        highlights: ['Fully in Größe S', 'Scheibenbremsen', 'Für 158–178 cm'] },
      it: { name: 'Hystric Fully 26 — rossa', tagline: 'Mountain bike biammortizzata',
        description: 'La stessa bici della Hystric blu, in taglie più piccole. Una biammortizzata in taglia S è rara a noleggio, ed è proprio ciò che permette a tutta la famiglia di fare lo stesso sentiero.',
        highlights: ['Biammortizzata in taglia S', 'Freni a disco', 'Per statura 158–178 cm'] },
    },
  },
  {
    slug: 'mtb-26-hybrid-svr-monotube', sku: 'MTB-SVR-MONO', category: 'mtb', brand: 'B.R.B. Sport',
    order: 16, featured: false, fleetSize: 6, image: 'mtb-26-hybrid-svr-monotube-standard.jpg',
    specs: { wheel: '26', frameMaterial: 'aluminium', frameType: 'monotube', gears: 18, suspension: 'hardtail',
      brakes: 'v-brake', sizes: ['S', 'M'], riderHeight: [155, 180] },
    pricing: P(14, 12, 11, 10, 9),
    needsReview: ['gears', 'brakes'],
    color: { hr: 'crna', en: 'black', de: 'Schwarz', it: 'nero' },
    i18n: {
      hr: { name: 'SVR Monotube Hybrid 26', tagline: 'Hibrid, prohodni okvir',
        description: 'Između gradskog i brdskog: prohodni okvir za lak ulazak, ali gume i vilica koje podnesu makadam do plaže. Ako u grupi ima nekoga tko dugo nije bio na biciklu, dajte mu ovaj.',
        highlights: ['Prohodni okvir', 'Podnosi makadam', 'Najlakši za ponovni početak'] },
      en: { name: 'SVR Monotube Hybrid 26', tagline: 'Hybrid, step-through frame',
        description: 'Between a city bike and a mountain bike: a step-through frame for easy mounting, but tyres and a fork that cope with the gravel track down to the beach. If someone in the group has not ridden in years, give them this one.',
        highlights: ['Step-through frame', 'Handles gravel', 'Easiest bike to start again on'] },
      de: { name: 'SVR Monotube Hybrid 26', tagline: 'Hybrid, Tiefeinsteiger',
        description: 'Zwischen City- und Mountainbike: Tiefeinsteiger-Rahmen für bequemes Aufsteigen, aber Reifen und Gabel, die den Schotterweg zum Strand aushalten. Wenn jemand in der Gruppe lange nicht gefahren ist, bekommt er dieses.',
        highlights: ['Tiefeinsteiger-Rahmen', 'Schottertauglich', 'Der einfachste Wiedereinstieg'] },
      it: { name: 'SVR Monotube Hybrid 26', tagline: 'Ibrida, telaio a scavalco basso',
        description: 'A metà tra city e mountain bike: telaio a scavalco basso per salire comodi, ma gomme e forcella che reggono lo sterrato fino alla spiaggia. Se nel gruppo c’è chi non pedala da anni, dategli questa.',
        highlights: ['Telaio a scavalco basso', 'Regge lo sterrato', 'La più facile per ricominciare'] },
    },
  },

  // ── CITY ─────────────────────────────────────────────────────────────
  {
    slug: 'city-28-carratt-lady', sku: 'CTY-CAR-LADY', category: 'city', brand: 'Carratt',
    order: 20, featured: true, fleetSize: 10, image: 'city-28-CARRATT-LADY-STANDARD.jpg',
    specs: { wheel: '28', frameMaterial: 'steel', frameType: 'stepthrough', gears: 6, suspension: 'rigid',
      brakes: 'v-brake', sizes: ['one'], riderHeight: [155, 180] },
    pricing: P(12, 11, 10, 9, 8),
    needsReview: ['gears', 'frame'],
    color: { hr: 'krem', en: 'cream', de: 'Creme', it: 'crema' },
    i18n: {
      hr: { name: 'Carratt City 28 — ženski', tagline: 'Gradski, prohodni okvir',
        description: 'Košara sprijeda, nosač straga, blatobrani i uspravno sjedenje. Za odlazak na tržnicu, do plaže i natrag u papučama — bez ambicija i bez znojenja. Najam ovog bicikla najčešće traje cijeli tjedan.',
        highlights: ['Košara i nosač', 'Blatobrani', 'Uspravno, udobno sjedenje', 'Deset komada u floti'] },
      en: { name: 'Carratt City 28 — ladies', tagline: 'City bike, step-through frame',
        description: 'Basket up front, rack at the back, mudguards and an upright seat. For the market, the beach and back in flip-flops — no ambition and no sweating. This is the bike people usually keep for the whole week.',
        highlights: ['Basket and rack', 'Mudguards', 'Upright, comfortable seating', 'Ten units in the fleet'] },
      de: { name: 'Carratt City 28 — Damen', tagline: 'Citybike, Tiefeinsteiger',
        description: 'Korb vorn, Gepäckträger hinten, Schutzbleche und aufrechte Sitzposition. Für den Markt, den Strand und zurück in Badelatschen — ohne Ehrgeiz und ohne Schwitzen. Dieses Rad wird meist gleich für die ganze Woche gemietet.',
        highlights: ['Korb und Gepäckträger', 'Schutzbleche', 'Aufrechte, bequeme Sitzposition', 'Zehn Exemplare'] },
      it: { name: 'Carratt City 28 — donna', tagline: 'City bike, telaio a scavalco basso',
        description: 'Cestino davanti, portapacchi dietro, parafanghi e posizione eretta. Per il mercato, la spiaggia e ritorno in infradito: senza ambizioni e senza sudare. Di solito la si tiene per tutta la settimana.',
        highlights: ['Cestino e portapacchi', 'Parafanghi', 'Seduta eretta e comoda', 'Dieci esemplari in flotta'] },
    },
  },
  {
    slug: 'city-28-carratt-men', sku: 'CTY-CAR-MEN', category: 'city', brand: 'Carratt',
    order: 21, featured: false, fleetSize: 10, image: 'city-28-CARRATT-MAN-STANDARD.jpg',
    specs: { wheel: '28', frameMaterial: 'steel', frameType: 'classic', gears: 6, suspension: 'rigid',
      brakes: 'v-brake', sizes: ['one'], riderHeight: [170, 195] },
    pricing: P(12, 11, 10, 9, 8),
    needsReview: ['gears', 'frame'],
    color: { hr: 'krem', en: 'cream', de: 'Creme', it: 'crema' },
    i18n: {
      hr: { name: 'Carratt City 28 — muški', tagline: 'Gradski, klasični okvir',
        description: 'Isti bicikl kao ženska izvedba, s klasičnim ravnim okvirom i za više vozače. Šest brzina je sasvim dovoljno za sve što je ravno između Šišana i Medulina.',
        highlights: ['Za visinu do 195 cm', 'Košara i nosač', 'Blatobrani', 'Deset komada u floti'] },
      en: { name: 'Carratt City 28 — men’s', tagline: 'City bike, classic frame',
        description: 'The same bike as the ladies version, with a classic straight top tube and for taller riders. Six gears are plenty for everything flat between Šišan and Medulin.',
        highlights: ['For riders up to 195 cm', 'Basket and rack', 'Mudguards', 'Ten units in the fleet'] },
      de: { name: 'Carratt City 28 — Herren', tagline: 'Citybike, klassischer Rahmen',
        description: 'Dasselbe Rad wie die Damenversion, mit klassischem geraden Oberrohr und für größere Fahrer. Sechs Gänge reichen für alles Flache zwischen Šišan und Medulin.',
        highlights: ['Für bis zu 195 cm', 'Korb und Gepäckträger', 'Schutzbleche', 'Zehn Exemplare'] },
      it: { name: 'Carratt City 28 — uomo', tagline: 'City bike, telaio classico',
        description: 'La stessa bici della versione donna, con tubo orizzontale classico e per chi è più alto. Sei rapporti bastano per tutto il piano tra Šišan e Medolino.',
        highlights: ['Per statura fino a 195 cm', 'Cestino e portapacchi', 'Parafanghi', 'Dieci esemplari in flotta'] },
    },
  },

  // ── KIDS ─────────────────────────────────────────────────────────────
  {
    slug: 'kids-torpado-20-blue', sku: 'KID-TOR-20-BL', category: 'kids', brand: 'Torpado',
    order: 30, featured: false, fleetSize: 6, image: 'children-20-4a.jpg',
    specs: { wheel: '20', frameMaterial: 'steel', gears: 6, suspension: 'rigid', brakes: 'v-brake',
      sizes: ['one'], riderHeight: [115, 135] },
    pricing: P(9, 8, 7, 6, 6),
    needsReview: ['gears'],
    color: { hr: 'plava', en: 'blue', de: 'Blau', it: 'blu' },
    i18n: {
      hr: { name: 'Torpado 16″/20″ — plavi', tagline: 'Dječji, 6–9 godina',
        description: 'Pravi mali brdski bicikl, ne igračka. Dolazi s kacigom po dogovoru, a ako dijete još nije sigurno u sedlu, imamo i dječju sjedalicu i prikolicu.',
        highlights: ['Za visinu 115–135 cm', 'Kaciga uz najam', 'Servisiran prije svakog najma'] },
      en: { name: 'Torpado 16″/20″ — blue', tagline: 'Kids bike, ages 6–9',
        description: 'A proper little mountain bike, not a toy. A helmet comes with it on request, and if your child is not steady in the saddle yet we also have child seats and trailers.',
        highlights: ['For heights 115–135 cm', 'Helmet with the rental', 'Serviced before every rental'] },
      de: { name: 'Torpado 16″/20″ — blau', tagline: 'Kinderrad, 6–9 Jahre',
        description: 'Ein richtiges kleines Mountainbike, kein Spielzeug. Helm auf Wunsch dabei, und wenn das Kind im Sattel noch unsicher ist, haben wir auch Kindersitze und Anhänger.',
        highlights: ['Für 115–135 cm', 'Helm zur Miete', 'Vor jeder Miete gewartet'] },
      it: { name: 'Torpado 16″/20″ — blu', tagline: 'Bici per bambini, 6–9 anni',
        description: 'Una vera piccola mountain bike, non un giocattolo. Il casco è compreso su richiesta e, se il bambino non è ancora sicuro in sella, abbiamo anche seggiolini e rimorchi.',
        highlights: ['Per statura 115–135 cm', 'Casco col noleggio', 'Revisionata prima di ogni noleggio'] },
    },
  },
  {
    slug: 'kids-torpado-20-pink', sku: 'KID-TOR-20-PK', category: 'kids', brand: 'Torpado',
    order: 31, featured: false, fleetSize: 6, image: 'children-20-4b.jpg',
    specs: { wheel: '20', frameMaterial: 'steel', gears: 6, suspension: 'rigid', brakes: 'v-brake',
      sizes: ['one'], riderHeight: [115, 135] },
    pricing: P(9, 8, 7, 6, 6),
    needsReview: ['gears'],
    color: { hr: 'roza', en: 'pink', de: 'Pink', it: 'rosa' },
    i18n: {
      hr: { name: 'Torpado 16″/20″ — roza', tagline: 'Dječji, 6–9 godina',
        description: 'Ista veličina i oprema kao plavi model, u roza izvedbi. Imamo ih dovoljno da se braća i sestre ne svađaju oko boje.',
        highlights: ['Za visinu 115–135 cm', 'Kaciga uz najam', 'Šest komada u floti'] },
      en: { name: 'Torpado 16″/20″ — pink', tagline: 'Kids bike, ages 6–9',
        description: 'Same size and build as the blue one, in pink. We keep enough of both so siblings do not have to argue about the colour.',
        highlights: ['For heights 115–135 cm', 'Helmet with the rental', 'Six units in the fleet'] },
      de: { name: 'Torpado 16″/20″ — pink', tagline: 'Kinderrad, 6–9 Jahre',
        description: 'Gleiche Größe und Ausstattung wie das blaue Modell, in Pink. Wir haben genug von beiden, damit Geschwister nicht um die Farbe streiten müssen.',
        highlights: ['Für 115–135 cm', 'Helm zur Miete', 'Sechs Exemplare'] },
      it: { name: 'Torpado 16″/20″ — rosa', tagline: 'Bici per bambini, 6–9 anni',
        description: 'Stessa misura e allestimento del modello blu, in rosa. Ne teniamo abbastanza di entrambi perché i fratelli non litighino sul colore.',
        highlights: ['Per statura 115–135 cm', 'Casco col noleggio', 'Sei esemplari in flotta'] },
    },
  },
  {
    slug: 'kids-torpado-24-blue', sku: 'KID-TOR-24-BL', category: 'kids', brand: 'Torpado',
    order: 32, featured: false, fleetSize: 5, image: 'children-24-5a.jpg',
    specs: { wheel: '24', frameMaterial: 'steel', gears: 18, suspension: 'hardtail', brakes: 'v-brake',
      sizes: ['one'], riderHeight: [135, 155] },
    pricing: P(10, 9, 8, 7, 6),
    needsReview: ['gears'],
    color: { hr: 'plava', en: 'blue', de: 'Blau', it: 'blu' },
    i18n: {
      hr: { name: 'Torpado 24″ — plavi', tagline: 'Dječji, 9–13 godina',
        description: 'Sljedeći korak nakon dvadesetice: veći kotači, više brzina i amortizirajuća vilica. S ovim biciklom dijete može pratiti roditelje na cjelodnevnoj vožnji, a ne samo do plaže.',
        highlights: ['Za visinu 135–155 cm', 'Amortizirajuća vilica', 'Za cjelodnevne vožnje'] },
      en: { name: 'Torpado 24″ — blue', tagline: 'Kids bike, ages 9–13',
        description: 'The next step up from the 20-inch: bigger wheels, more gears and a suspension fork. On this one a child can keep up with the parents on a full-day ride, not just the trip to the beach.',
        highlights: ['For heights 135–155 cm', 'Suspension fork', 'Ready for full-day rides'] },
      de: { name: 'Torpado 24″ — blau', tagline: 'Kinderrad, 9–13 Jahre',
        description: 'Der nächste Schritt nach dem 20-Zöller: größere Laufräder, mehr Gänge und eine Federgabel. Damit hält ein Kind auch bei einer Ganztagestour mit, nicht nur auf dem Weg zum Strand.',
        highlights: ['Für 135–155 cm', 'Federgabel', 'Für Ganztagestouren'] },
      it: { name: 'Torpado 24″ — blu', tagline: 'Bici per bambini, 9–13 anni',
        description: 'Il passo successivo alla 20 pollici: ruote più grandi, più rapporti e forcella ammortizzata. Con questa un bambino tiene il passo dei genitori per un’intera giornata, non solo fino alla spiaggia.',
        highlights: ['Per statura 135–155 cm', 'Forcella ammortizzata', 'Pronta per uscite di un giorno'] },
    },
  },
  {
    slug: 'kids-torpado-24-pink', sku: 'KID-TOR-24-PK', category: 'kids', brand: 'Torpado',
    order: 33, featured: false, fleetSize: 5, image: 'children-24-5b.jpg',
    specs: { wheel: '24', frameMaterial: 'steel', gears: 18, suspension: 'hardtail', brakes: 'v-brake',
      sizes: ['one'], riderHeight: [135, 155] },
    pricing: P(10, 9, 8, 7, 6),
    needsReview: ['gears'],
    color: { hr: 'roza', en: 'pink', de: 'Pink', it: 'rosa' },
    i18n: {
      hr: { name: 'Torpado 24″ — roza', tagline: 'Dječji, 9–13 godina',
        description: 'Ista izvedba kao plavi 24-inčni model, u roza boji. Amortizirajuća vilica i osamnaest brzina — dovoljno za makadame oko Kamenjaka.',
        highlights: ['Za visinu 135–155 cm', 'Amortizirajuća vilica', '18 brzina'] },
      en: { name: 'Torpado 24″ — pink', tagline: 'Kids bike, ages 9–13',
        description: 'The same build as the blue 24-inch, in pink. Suspension fork and eighteen gears — enough for the gravel tracks around Kamenjak.',
        highlights: ['For heights 135–155 cm', 'Suspension fork', '18 gears'] },
      de: { name: 'Torpado 24″ — pink', tagline: 'Kinderrad, 9–13 Jahre',
        description: 'Gleiche Ausstattung wie der blaue 24-Zöller, in Pink. Federgabel und achtzehn Gänge — genug für die Schotterwege rund um den Kamenjak.',
        highlights: ['Für 135–155 cm', 'Federgabel', '18 Gänge'] },
      it: { name: 'Torpado 24″ — rosa', tagline: 'Bici per bambini, 9–13 anni',
        description: 'Stesso allestimento della 24 blu, in rosa. Forcella ammortizzata e diciotto rapporti: bastano per gli sterrati attorno al Kamenjak.',
        highlights: ['Per statura 135–155 cm', 'Forcella ammortizzata', '18 rapporti'] },
    },
  },

  // ── RACING ───────────────────────────────────────────────────────────
  {
    slug: 'racing-carbon', sku: 'RAC-CARBON', category: 'racing', brand: 'B.R.B. Sport',
    order: 40, featured: true, fleetSize: 2, image: 'racing-carbon.jpg',
    specs: { wheel: '28', frameMaterial: 'carbon', gears: 22, suspension: 'rigid',
      brakes: 'disc', weight: 8.5, sizes: ['M', 'L'], riderHeight: [172, 188] },
    pricing: P(40, 36, 32, 29, 26),
    needsReview: ['gears', 'weight', 'brakes'],
    color: { hr: 'crna', en: 'black', de: 'Schwarz', it: 'nero' },
    i18n: {
      hr: { name: 'Cestovni karbon', tagline: 'Cestovni, karbonski okvir',
        description: 'Karbonski okvir ispod devet kilograma. Imamo samo dva komada, pa se ovaj bicikl praktički uvijek rezervira unaprijed. Istarski asfalt oko Barbana i Svetvinčenta je razlog zbog kojeg ga držimo u floti.',
        highlights: ['Karbonski okvir', 'Ispod 9 kg', 'Samo dva komada — rezervirajte ranije'] },
      en: { name: 'Road carbon', tagline: 'Road bike, carbon frame',
        description: 'A carbon frame under nine kilos. We only have two, so this one is effectively always booked in advance. The Istrian tarmac around Barban and Svetvinčenat is the reason we keep it in the fleet at all.',
        highlights: ['Carbon frame', 'Under 9 kg', 'Only two units — book early'] },
      de: { name: 'Rennrad Carbon', tagline: 'Rennrad, Carbonrahmen',
        description: 'Ein Carbonrahmen unter neun Kilo. Wir haben nur zwei Stück, daher ist dieses Rad praktisch immer im Voraus gebucht. Der istrische Asphalt rund um Barban und Svetvinčenat ist der Grund, warum wir es überhaupt im Verleih haben.',
        highlights: ['Carbonrahmen', 'Unter 9 kg', 'Nur zwei Exemplare — früh buchen'] },
      it: { name: 'Bici da corsa carbonio', tagline: 'Da corsa, telaio in carbonio',
        description: 'Telaio in carbonio sotto i nove chili. Ne abbiamo solo due, quindi è praticamente sempre prenotata in anticipo. L’asfalto istriano attorno a Barbana e Sanvincenti è il motivo per cui la teniamo in flotta.',
        highlights: ['Telaio in carbonio', 'Sotto i 9 kg', 'Solo due esemplari — prenotate presto'] },
    },
  },
  {
    slug: 'racing-alu', sku: 'RAC-ALU', category: 'racing', brand: 'B.R.B. Sport',
    order: 41, featured: false, fleetSize: 3, image: 'racing-alu.jpg',
    specs: { wheel: '28', frameMaterial: 'aluminium', gears: 18, suspension: 'rigid',
      brakes: 'rim', weight: 10.5, sizes: ['M', 'L'], riderHeight: [170, 188] },
    pricing: P(28, 25, 22, 20, 18),
    needsReview: ['gears', 'weight', 'brakes'],
    color: { hr: 'bijela', en: 'white', de: 'Weiß', it: 'bianco' },
    i18n: {
      hr: { name: 'Cestovni aluminij', tagline: 'Cestovni, aluminijski okvir',
        description: 'Aluminijski okvir i klasična cestovna geometrija po dvije trećine cijene karbonskog. Za tjedan dana odmora i sto pedeset kilometara tjedno razlika u težini nije ono što ćete zapamtiti.',
        highlights: ['Aluminijski okvir', 'Klasična cestovna geometrija', 'Povoljniji od karbonskog'] },
      en: { name: 'Road aluminium', tagline: 'Road bike, aluminium frame',
        description: 'An aluminium frame and classic road geometry at two thirds the price of the carbon. For a week off and a hundred and fifty kilometres, the weight difference is not what you will remember.',
        highlights: ['Aluminium frame', 'Classic road geometry', 'Cheaper than the carbon'] },
      de: { name: 'Rennrad Aluminium', tagline: 'Rennrad, Alurahmen',
        description: 'Alurahmen und klassische Rennradgeometrie zu zwei Dritteln des Carbonpreises. Bei einer Urlaubswoche und hundertfünfzig Kilometern ist der Gewichtsunterschied nicht das, woran Sie sich erinnern werden.',
        highlights: ['Alurahmen', 'Klassische Rennradgeometrie', 'Günstiger als Carbon'] },
      it: { name: 'Bici da corsa alluminio', tagline: 'Da corsa, telaio in alluminio',
        description: 'Telaio in alluminio e geometria stradale classica a due terzi del prezzo del carbonio. Per una settimana di vacanza e centocinquanta chilometri, la differenza di peso non è ciò che ricorderete.',
        highlights: ['Telaio in alluminio', 'Geometria stradale classica', 'Più economica del carbonio'] },
    },
  },
];

const ALT = {
  hr: (b) => `${b.i18n.hr.name} — ${b.i18n.hr.tagline.toLowerCase()}, boja ${b.color.hr}, za najam u Puli`,
  en: (b) => `${b.i18n.en.name} — ${b.i18n.en.tagline.toLowerCase()}, ${b.color.en}, for rent in Pula`,
  de: (b) => `${b.i18n.de.name} — ${b.i18n.de.tagline}, Farbe ${b.color.de}, zur Miete in Pula`,
  it: (b) => `${b.i18n.it.name} — ${b.i18n.it.tagline.toLowerCase()}, colore ${b.color.it}, a noleggio a Pola`,
};

const y = (v, indent = 0) => {
  const pad = ' '.repeat(indent);
  if (Array.isArray(v)) {
    if (v.every((x) => typeof x === 'number')) return ` [${v.join(', ')}]`;
    return '\n' + v.map((x) => `${pad}  - ${JSON.stringify(x)}`).join('\n');
  }
  if (typeof v === 'object' && v !== null) {
    return '\n' + Object.entries(v)
      .map(([k, val]) => `${pad}  ${k}:${typeof val === 'object' ? y(val, indent + 2) : ' ' + JSON.stringify(val)}`)
      .join('\n');
  }
  return ' ' + JSON.stringify(v);
};

for (const b of fleet) {
  const fm = [
    '---',
    `sku: ${JSON.stringify(b.sku)}`,
    `category: ${JSON.stringify(b.category)}`,
    `brand: ${JSON.stringify(b.brand)}`,
    `order: ${b.order}`,
    `featured: ${b.featured}`,
    `fleetSize: ${b.fleetSize}`,
    `specs:${y(b.specs)}`,
    `pricing:${y(b.pricing)}`,
    `image: ${JSON.stringify('../../assets/bikes/' + b.image)}`,
    `imageAlt:${y(Object.fromEntries(Object.keys(ALT).map((l) => [l, ALT[l](b)])))}`,
    `i18n:${y(b.i18n)}`,
    `needsReview:${y(b.needsReview)}`,
    '---',
    '',
  ].join('\n');
  writeFileSync(join(OUT, `${b.slug}.md`), fm, 'utf8');
}

console.log(`Zapisano ${fleet.length} bicikala u ${OUT}`);
